-- SecLab profile and learning analytics database initialization.
-- Scope: learning events, submissions, AI conversations, profile snapshots, and training data.
-- Generated by consolidating active profile SQL files; source files are retained for traceability.


-- Source: 数据库文件/learning_event.sql

CREATE DATABASE IF NOT EXISTS `seclab_profile`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seclab_profile`;

CREATE TABLE IF NOT EXISTS `learning_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NULL,
  `question_id` BIGINT NULL,
  `lab_session_id` VARCHAR(64) NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `event_time` DATETIME(6) NOT NULL,
  `payload_json` JSON NOT NULL,
  `source` VARCHAR(64) NOT NULL DEFAULT 'ai-agent-service',
  `request_id` VARCHAR(64) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_learning_event_event_id` (`event_id`),
  KEY `idx_learning_event_user_time` (`user_id`, `event_time`),
  KEY `idx_learning_event_module_time` (`module_id`, `event_time`),
  KEY `idx_learning_event_lab_session_time` (`lab_session_id`, `event_time`),
  KEY `idx_learning_event_type_time` (`event_type`, `event_time`),
  KEY `idx_learning_event_request_id` (`request_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Source: 数据库文件/question_submission.sql

CREATE DATABASE IF NOT EXISTS `seclab_profile`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seclab_profile`;

CREATE TABLE IF NOT EXISTS `question_submission` (
  `submission_id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NULL,
  `question_id` BIGINT NOT NULL,
  `question_uid` VARCHAR(128) NULL,
  `question_type` VARCHAR(64) NOT NULL,
  `answer_json` JSON NOT NULL,
  `standard_answer_json` JSON NULL,
  `question_snapshot_json` JSON NULL,
  `is_correct` TINYINT(1) NULL,
  `score` DECIMAL(8,2) NOT NULL DEFAULT 0,
  `cost_time` INT NULL,
  `question_source` VARCHAR(64) NOT NULL DEFAULT 'course_question',
  `training_session_id` VARCHAR(64) NULL,
  `knowledge_point_id` BIGINT NULL,
  `request_id` VARCHAR(64) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`submission_id`),
  KEY `idx_question_submission_user_time` (`user_id`, `created_at`),
  KEY `idx_question_submission_module_time` (`module_id`, `created_at`),
  KEY `idx_question_submission_question_time` (`question_id`, `created_at`),
  KEY `idx_question_submission_uid` (`question_uid`),
  KEY `idx_question_submission_training` (`training_session_id`, `created_at`),
  KEY `idx_question_submission_kp_time` (`knowledge_point_id`, `created_at`),
  KEY `idx_question_submission_source_time` (`question_source`, `created_at`),
  KEY `idx_question_submission_request_id` (`request_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Source: 数据库文件/lab_session_flag.sql

CREATE DATABASE IF NOT EXISTS `seclab_profile`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seclab_profile`;

CREATE TABLE IF NOT EXISTS `lab_session` (
  `session_id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NULL,
  `container_name` VARCHAR(128) NULL,
  `container_id` VARCHAR(128) NULL,
  `target_url` VARCHAR(512) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'running',
  `start_time` DATETIME(6) NOT NULL,
  `end_time` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`session_id`),
  KEY `idx_lab_session_user_time` (`user_id`, `start_time`),
  KEY `idx_lab_session_module_time` (`module_id`, `start_time`),
  KEY `idx_lab_session_status` (`status`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `flag_submission` (
  `submission_id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NULL,
  `lab_session_id` VARCHAR(64) NULL,
  `container_name` VARCHAR(128) NULL,
  `flag_text` VARCHAR(512) NOT NULL,
  `is_correct` TINYINT(1) NOT NULL DEFAULT 0,
  `score` DECIMAL(8,2) NOT NULL DEFAULT 0,
  `request_id` VARCHAR(64) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`submission_id`),
  KEY `idx_flag_submission_user_time` (`user_id`, `created_at`),
  KEY `idx_flag_submission_session_time` (`lab_session_id`, `created_at`),
  KEY `idx_flag_submission_module_time` (`module_id`, `created_at`),
  KEY `idx_flag_submission_request_id` (`request_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `challenge_completion_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NULL,
  `lab_session_id` VARCHAR(64) NULL,
  `completion_status` VARCHAR(32) NOT NULL,
  `total_time_seconds` INT NULL,
  `total_ai_ask_count` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_completion_user_time` (`user_id`, `created_at`),
  KEY `idx_completion_session` (`lab_session_id`),
  KEY `idx_completion_module_time` (`module_id`, `created_at`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Source: 数据库文件/container_command_event.sql

CREATE DATABASE IF NOT EXISTS `seclab_profile`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seclab_profile`;

CREATE TABLE IF NOT EXISTS `container_command_event` (
  `command_id` VARCHAR(64) NOT NULL,
  `lab_session_id` VARCHAR(64) NULL,
  `user_id` BIGINT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NULL,
  `container_name` VARCHAR(128) NULL,
  `command` VARCHAR(2048) NOT NULL,
  `normalized_command` VARCHAR(2048) NOT NULL,
  `cmd_category` VARCHAR(64) NOT NULL DEFAULT 'other',
  `cwd` VARCHAR(1024) NULL,
  `exit_code` INT NULL,
  `duration_ms` INT NULL,
  `output_digest` VARCHAR(512) NULL,
  `source` VARCHAR(64) NOT NULL DEFAULT 'hook',
  `request_id` VARCHAR(64) NULL,
  `executed_at` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`command_id`),
  KEY `idx_container_command_session_time` (`lab_session_id`, `executed_at`),
  KEY `idx_container_command_user_time` (`user_id`, `executed_at`),
  KEY `idx_container_command_module_time` (`module_id`, `executed_at`),
  KEY `idx_container_command_container_time` (`container_name`, `executed_at`),
  KEY `idx_container_command_category_time` (`cmd_category`, `executed_at`),
  KEY `idx_container_command_request_id` (`request_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Source: 数据库文件/container_file_event.sql

CREATE DATABASE IF NOT EXISTS `seclab_profile`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seclab_profile`;

CREATE TABLE IF NOT EXISTS `container_file_event` (
  `file_event_id` VARCHAR(64) NOT NULL,
  `lab_session_id` VARCHAR(64) NULL,
  `user_id` BIGINT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NULL,
  `container_name` VARCHAR(128) NULL,
  `file_path` VARCHAR(2048) NOT NULL,
  `file_ext` VARCHAR(32) NULL,
  `action` VARCHAR(32) NOT NULL,
  `size_before` BIGINT NULL,
  `size_after` BIGINT NULL,
  `sha256` VARCHAR(64) NULL,
  `is_key_file` TINYINT(1) NOT NULL DEFAULT 0,
  `source` VARCHAR(64) NOT NULL DEFAULT 'watcher',
  `request_id` VARCHAR(64) NULL,
  `changed_at` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`file_event_id`),
  KEY `idx_container_file_session_time` (`lab_session_id`, `changed_at`),
  KEY `idx_container_file_user_time` (`user_id`, `changed_at`),
  KEY `idx_container_file_module_time` (`module_id`, `changed_at`),
  KEY `idx_container_file_container_time` (`container_name`, `changed_at`),
  KEY `idx_container_file_action_time` (`action`, `changed_at`),
  KEY `idx_container_file_request_id` (`request_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Source: 数据库文件/error_event.sql

CREATE DATABASE IF NOT EXISTS `seclab_profile`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seclab_profile`;

CREATE TABLE IF NOT EXISTS `error_event` (
  `error_id` VARCHAR(64) NOT NULL,
  `lab_session_id` VARCHAR(64) NULL,
  `user_id` BIGINT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NULL,
  `container_name` VARCHAR(128) NULL,
  `command_id` VARCHAR(64) NULL,
  `error_signature` VARCHAR(64) NOT NULL,
  `error_category` VARCHAR(64) NOT NULL,
  `raw_excerpt` VARCHAR(1024) NULL,
  `severity` VARCHAR(32) NOT NULL DEFAULT 'low',
  `source` VARCHAR(64) NOT NULL DEFAULT 'api',
  `request_id` VARCHAR(64) NULL,
  `occurred_at` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`error_id`),
  KEY `idx_error_event_session_time` (`lab_session_id`, `occurred_at`),
  KEY `idx_error_event_user_time` (`user_id`, `occurred_at`),
  KEY `idx_error_event_module_time` (`module_id`, `occurred_at`),
  KEY `idx_error_event_command` (`command_id`),
  KEY `idx_error_event_signature_time` (`error_signature`, `occurred_at`),
  KEY `idx_error_event_category_time` (`error_category`, `occurred_at`),
  KEY `idx_error_event_request_id` (`request_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Source: 数据库文件/ai_chat.sql

CREATE DATABASE IF NOT EXISTS `seclab_profile`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seclab_profile`;

CREATE TABLE IF NOT EXISTS `ai_conversation` (
  `conversation_id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NULL,
  `question_id` BIGINT NULL,
  `lab_session_id` VARCHAR(64) NULL,
  `dify_conversation_id` VARCHAR(128) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `source` VARCHAR(64) NOT NULL DEFAULT 'ai-agent-service',
  `start_time` DATETIME(6) NOT NULL,
  `last_message_at` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`conversation_id`),
  UNIQUE KEY `uk_ai_conversation_dify_id` (`dify_conversation_id`),
  KEY `idx_ai_conversation_user_time` (`user_id`, `last_message_at`),
  KEY `idx_ai_conversation_module_time` (`module_id`, `last_message_at`),
  KEY `idx_ai_conversation_lab_session` (`lab_session_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_message` (
  `message_id` VARCHAR(64) NOT NULL,
  `conversation_id` VARCHAR(64) NOT NULL,
  `role` VARCHAR(32) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `content_length` INT NOT NULL DEFAULT 0,
  `token_count` INT NULL,
  `event_name` VARCHAR(64) NULL,
  `hint_level` VARCHAR(32) NULL,
  `contains_context` TINYINT(1) NOT NULL DEFAULT 0,
  `contains_error_excerpt` TINYINT(1) NOT NULL DEFAULT 0,
  `raw_payload_json` JSON NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`message_id`),
  KEY `idx_ai_message_conversation_time` (`conversation_id`, `created_at`),
  KEY `idx_ai_message_role_time` (`role`, `created_at`),
  CONSTRAINT `fk_ai_message_conversation`
    FOREIGN KEY (`conversation_id`) REFERENCES `ai_conversation` (`conversation_id`)
    ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_tool_call` (
  `tool_call_id` VARCHAR(64) NOT NULL,
  `conversation_id` VARCHAR(64) NOT NULL,
  `message_id` VARCHAR(64) NULL,
  `tool_name` VARCHAR(128) NOT NULL,
  `tool_input_json` JSON NULL,
  `tool_output_json` JSON NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'unknown',
  `error_message` TEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`tool_call_id`),
  KEY `idx_ai_tool_call_conversation_time` (`conversation_id`, `created_at`),
  KEY `idx_ai_tool_call_message` (`message_id`),
  KEY `idx_ai_tool_call_tool` (`tool_name`),
  CONSTRAINT `fk_ai_tool_call_conversation`
    FOREIGN KEY (`conversation_id`) REFERENCES `ai_conversation` (`conversation_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_ai_tool_call_message`
    FOREIGN KEY (`message_id`) REFERENCES `ai_message` (`message_id`)
    ON DELETE SET NULL
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_context_injection` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `conversation_id` VARCHAR(64) NOT NULL,
  `message_id` VARCHAR(64) NULL,
  `context_type` VARCHAR(64) NOT NULL,
  `context_summary` TEXT NULL,
  `context_size` INT NOT NULL DEFAULT 0,
  `raw_context_json` JSON NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_ai_context_conversation_time` (`conversation_id`, `created_at`),
  KEY `idx_ai_context_message` (`message_id`),
  CONSTRAINT `fk_ai_context_conversation`
    FOREIGN KEY (`conversation_id`) REFERENCES `ai_conversation` (`conversation_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_ai_context_message`
    FOREIGN KEY (`message_id`) REFERENCES `ai_message` (`message_id`)
    ON DELETE SET NULL
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Source: 数据库文件/student_profile_snapshot.sql

CREATE DATABASE IF NOT EXISTS `seclab_profile`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seclab_profile`;

CREATE TABLE IF NOT EXISTS `student_profile_snapshot` (
  `snapshot_id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `computed_at` DATETIME(6) NOT NULL,
  `knowledge_mastery_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `troubleshooting_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `autonomy_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `ai_collaboration_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `engagement_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `overall_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `profile_summary_json` JSON NOT NULL,
  `source_range_start` DATETIME(6) NULL,
  `source_range_end` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`snapshot_id`),
  KEY `idx_student_profile_user_time` (`user_id`, `computed_at`),
  KEY `idx_student_profile_class_time` (`class_id`, `computed_at`),
  KEY `idx_student_profile_course_time` (`course_id`, `computed_at`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `student_profile_feature_daily` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `stat_date` DATE NOT NULL,
  `question_submit_count` INT NOT NULL DEFAULT 0,
  `question_correct_count` INT NOT NULL DEFAULT 0,
  `flag_submit_count` INT NOT NULL DEFAULT 0,
  `flag_correct_count` INT NOT NULL DEFAULT 0,
  `lab_session_count` INT NOT NULL DEFAULT 0,
  `completed_lab_count` INT NOT NULL DEFAULT 0,
  `ai_message_count` INT NOT NULL DEFAULT 0,
  `ai_user_message_count` INT NOT NULL DEFAULT 0,
  `ai_assistant_message_count` INT NOT NULL DEFAULT 0,
  `command_count` INT NOT NULL DEFAULT 0,
  `unique_command_count` INT NOT NULL DEFAULT 0,
  `file_change_count` INT NOT NULL DEFAULT 0,
  `error_count` INT NOT NULL DEFAULT 0,
  `high_severity_error_count` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_profile_feature_user_date` (`user_id`, `stat_date`),
  KEY `idx_profile_feature_user_date` (`user_id`, `stat_date`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Source: 数据库文件/class_profile_snapshot.sql

CREATE DATABASE IF NOT EXISTS `seclab_profile`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seclab_profile`;

CREATE TABLE IF NOT EXISTS `class_profile_snapshot` (
  `snapshot_id` VARCHAR(64) NOT NULL,
  `class_id` BIGINT NOT NULL,
  `course_id` BIGINT NULL,
  `computed_at` DATETIME(6) NOT NULL,
  `student_count` INT NOT NULL DEFAULT 0,
  `class_avg_knowledge_mastery` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `class_avg_troubleshooting` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `class_avg_autonomy` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `class_avg_ai_collaboration` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `class_avg_engagement` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `class_overall_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `weak_dimensions_json` JSON NOT NULL,
  `strengths_json` JSON NOT NULL,
  `risk_students_json` JSON NOT NULL,
  `summary_json` JSON NOT NULL,
  `source_range_start` DATETIME(6) NULL,
  `source_range_end` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`snapshot_id`),
  KEY `idx_class_profile_class_time` (`class_id`, `computed_at`),
  KEY `idx_class_profile_course_time` (`course_id`, `computed_at`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `class_profile_student_metric` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `class_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `snapshot_id` VARCHAR(64) NOT NULL,
  `overall_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `knowledge_mastery_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `troubleshooting_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `autonomy_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `ai_collaboration_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `engagement_score` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `risk_level` VARCHAR(16) NOT NULL DEFAULT 'low',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_class_profile_metric_snapshot_user` (`snapshot_id`, `user_id`),
  KEY `idx_class_profile_metric_class_user` (`class_id`, `user_id`),
  KEY `idx_class_profile_metric_snapshot` (`snapshot_id`),
  KEY `idx_class_profile_metric_risk` (`class_id`, `risk_level`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

-- Source: 数据库文件/personalized_training.sql

CREATE DATABASE IF NOT EXISTS `seclab_profile`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `seclab_profile`;

-- Incremental compatibility for the existing question_submission evidence chain.
SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'question_submission' AND COLUMN_NAME = 'question_uid') = 0,
  'ALTER TABLE `question_submission` ADD COLUMN `question_uid` VARCHAR(128) NULL AFTER `question_id`',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'question_submission' AND COLUMN_NAME = 'question_source') = 0,
  'ALTER TABLE `question_submission` ADD COLUMN `question_source` VARCHAR(64) NOT NULL DEFAULT ''course_question'' AFTER `cost_time`',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'question_submission' AND COLUMN_NAME = 'training_session_id') = 0,
  'ALTER TABLE `question_submission` ADD COLUMN `training_session_id` VARCHAR(64) NULL AFTER `question_source`',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'question_submission' AND COLUMN_NAME = 'knowledge_point_id') = 0,
  'ALTER TABLE `question_submission` ADD COLUMN `knowledge_point_id` BIGINT NULL AFTER `training_session_id`',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'question_submission' AND INDEX_NAME = 'idx_question_submission_uid') = 0,
  'CREATE INDEX `idx_question_submission_uid` ON `question_submission` (`question_uid`)',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'question_submission' AND INDEX_NAME = 'idx_question_submission_training') = 0,
  'CREATE INDEX `idx_question_submission_training` ON `question_submission` (`training_session_id`, `created_at`)',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'question_submission' AND INDEX_NAME = 'idx_question_submission_kp_time') = 0,
  'CREATE INDEX `idx_question_submission_kp_time` ON `question_submission` (`knowledge_point_id`, `created_at`)',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql = IF(
  (SELECT COUNT(*) FROM information_schema.STATISTICS
   WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'question_submission' AND INDEX_NAME = 'idx_question_submission_source_time') = 0,
  'CREATE INDEX `idx_question_submission_source_time` ON `question_submission` (`question_source`, `created_at`)',
  'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS `knowledge_point` (
  `knowledge_point_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(64) NULL,
  `description` TEXT NULL,
  `difficulty_level` VARCHAR(32) NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`knowledge_point_id`),
  KEY `idx_knowledge_point_category` (`category`),
  KEY `idx_knowledge_point_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `module_knowledge_point` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `module_id` BIGINT NOT NULL,
  `knowledge_point_id` BIGINT NOT NULL,
  `relevance_weight` DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_module_knowledge_point` (`module_id`, `knowledge_point_id`),
  KEY `idx_module_kp_module` (`module_id`),
  KEY `idx_module_kp_kp` (`knowledge_point_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `task_knowledge_point` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NOT NULL,
  `knowledge_point_id` BIGINT NOT NULL,
  `relevance_weight` DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_knowledge_point` (`module_id`, `task_id`, `knowledge_point_id`),
  KEY `idx_task_kp_task` (`task_id`),
  KEY `idx_task_kp_module_task` (`module_id`, `task_id`),
  KEY `idx_task_kp_kp` (`knowledge_point_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `question_knowledge_point` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `question_id` BIGINT NULL,
  `question_uid` VARCHAR(128) NULL,
  `generated_question_id` VARCHAR(64) NULL,
  `knowledge_point_id` BIGINT NOT NULL,
  `relevance_weight` DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_question_kp_question_id` (`question_id`),
  KEY `idx_question_kp_question_uid` (`question_uid`),
  KEY `idx_question_kp_generated` (`generated_question_id`),
  KEY `idx_question_kp_kp` (`knowledge_point_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `training_session` (
  `training_session_id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `class_id` BIGINT NULL,
  `course_id` BIGINT NULL,
  `profile_snapshot_id` VARCHAR(64) NULL,
  `source_type` VARCHAR(64) NOT NULL DEFAULT 'personalized_training',
  `diagnose_result_json` JSON NOT NULL,
  `training_context_json` JSON NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`training_session_id`),
  KEY `idx_training_session_user_time` (`user_id`, `created_at`),
  KEY `idx_training_session_course_time` (`course_id`, `created_at`),
  KEY `idx_training_session_profile` (`profile_snapshot_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `generated_question` (
  `generated_question_id` VARCHAR(64) NOT NULL,
  `question_numeric_id` BIGINT NOT NULL,
  `training_session_id` VARCHAR(64) NOT NULL,
  `question_type` VARCHAR(64) NOT NULL,
  `knowledge_point_id` BIGINT NULL,
  `module_id` BIGINT NULL,
  `task_id` BIGINT NULL,
  `difficulty` VARCHAR(32) NULL,
  `title` VARCHAR(255) NOT NULL,
  `stem` TEXT NOT NULL,
  `options_json` JSON NULL,
  `standard_answer` TEXT NULL,
  `reference_answer` TEXT NULL,
  `explanation` TEXT NULL,
  `scoring_rubric_json` JSON NULL,
  `source_model` VARCHAR(128) NULL,
  `raw_ai_json` JSON NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`generated_question_id`),
  UNIQUE KEY `uk_generated_question_numeric` (`question_numeric_id`),
  KEY `idx_generated_question_session` (`training_session_id`),
  KEY `idx_generated_question_kp` (`knowledge_point_id`),
  KEY `idx_generated_question_module_task` (`module_id`, `task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `generated_question_attempt` (
  `attempt_id` VARCHAR(64) NOT NULL,
  `training_session_id` VARCHAR(64) NOT NULL,
  `generated_question_id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `answer_json` JSON NOT NULL,
  `is_correct` TINYINT(1) NULL,
  `score` DECIMAL(8,2) NOT NULL DEFAULT 0,
  `cost_time` INT NULL,
  `submission_id` VARCHAR(64) NULL,
  `profile_rebuild_snapshot_id` VARCHAR(64) NULL,
  `submitted_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`attempt_id`),
  KEY `idx_generated_attempt_session` (`training_session_id`, `submitted_at`),
  KEY `idx_generated_attempt_question` (`generated_question_id`, `submitted_at`),
  KEY `idx_generated_attempt_user_time` (`user_id`, `submitted_at`),
  KEY `idx_generated_attempt_submission` (`submission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `knowledge_point`
  (`knowledge_point_id`, `name`, `category`, `description`, `difficulty_level`, `is_active`)
VALUES
  (101, 'SQL injection UNION column count', 'SQL injection', 'Use ORDER BY and UNION SELECT to infer column count and output positions.', 'medium', 1),
  (102, 'SQL blind injection timing inference', 'SQL injection', 'Use boolean conditions and sleep delays to infer database content.', 'medium', 1),
  (201, 'XSS input output context analysis', 'XSS', 'Identify HTML, attribute, and script contexts and choose an appropriate payload.', 'easy', 1),
  (301, 'CSRF token validation and request forgery', 'CSRF', 'Understand forged cross-site requests, token binding, and Referer validation.', 'medium', 1),
  (401, 'Command injection without spaces', 'Command injection', 'Use IFS, variable substitution, and redirection to bypass space filters.', 'medium', 1),
  (402, 'Command injection blacklist bypass', 'Command injection', 'Use encoding, concatenation, environment variables, or wildcards to bypass filters.', 'hard', 1),
  (501, 'File upload type validation bypass', 'File upload', 'Bypass extension, MIME, Content-Type, and parser mismatch checks.', 'medium', 1),
  (601, 'Directory traversal path normalization bypass', 'Directory traversal', 'Use dot-dot paths, encoding, absolute paths, and normalization gaps.', 'medium', 1)
ON DUPLICATE KEY UPDATE`name` = VALUES(`name`),
  `category` = VALUES(`category`),
  `description` = VALUES(`description`),
  `difficulty_level` = VALUES(`difficulty_level`),
  `is_active` = 1;

INSERT IGNORE INTO `module_knowledge_point` (`module_id`, `knowledge_point_id`, `relevance_weight`) VALUES
  (1, 101, 1.00), (1, 102, 1.00), (2, 201, 1.00), (3, 301, 1.00),
  (4, 401, 1.00), (4, 402, 1.00), (5, 501, 1.00), (6, 601, 1.00);

INSERT IGNORE INTO `task_knowledge_point` (`module_id`, `task_id`, `knowledge_point_id`, `relevance_weight`) VALUES
  (1, 1, 101, 1.00), (1, 2, 102, 1.00), (2, 1, 201, 1.00), (3, 1, 301, 1.00),
  (4, 1, 401, 1.00), (4, 2, 402, 1.00), (5, 1, 501, 1.00), (6, 1, 601, 1.00);

-- Teacher workspace: personal bookmarks over the live student-generated
-- question stream. This is not an approval or publishing workflow.
CREATE TABLE IF NOT EXISTS `teacher_typical_question` (
  `teacher_id` BIGINT NOT NULL,
  `generated_question_id` VARCHAR(64) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`teacher_id`, `generated_question_id`),
  UNIQUE KEY `uk_teacher_typical_question`
    (`teacher_id`, `generated_question_id`),
  KEY `idx_typical_question_question` (`generated_question_id`, `created_at`),
  CONSTRAINT `fk_typical_question_generated`
    FOREIGN KEY (`generated_question_id`)
    REFERENCES `generated_question` (`generated_question_id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Manual teacher analysis for one student in one owned teaching class.
-- No history table is kept; a failed refresh preserves the previous result.
CREATE TABLE IF NOT EXISTS `teacher_student_analysis` (
  `teacher_id` BIGINT NOT NULL,
  `teaching_class_id` BIGINT NOT NULL,
  `student_id` BIGINT NOT NULL,
  `analysis_status` VARCHAR(16) NOT NULL DEFAULT 'IDLE',
  `data_cutoff_at` DATETIME(6) NULL,
  `analysis_json` JSON NULL,
  `source_stats_json` JSON NULL,
  `last_attempt_at` DATETIME(6) NULL,
  `last_error_message` VARCHAR(500) NULL,
  `generated_at` DATETIME(6) NULL,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`teacher_id`, `teaching_class_id`, `student_id`),
  KEY `idx_student_analysis_class_status`
    (`teaching_class_id`, `analysis_status`, `updated_at`),
  KEY `idx_student_analysis_student` (`student_id`, `updated_at`),
  CONSTRAINT `chk_teacher_student_analysis_status`
    CHECK (`analysis_status` IN ('IDLE', 'RUNNING', 'READY'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One row per teaching class: only the latest successful manual analysis is
-- retained. A failed refresh keeps analysis_json and records the error.
CREATE TABLE IF NOT EXISTS `teacher_class_analysis` (
  `teaching_class_id` BIGINT NOT NULL,
  `requested_by` BIGINT NULL,
  `analysis_status` VARCHAR(16) NOT NULL DEFAULT 'IDLE',
  `data_cutoff_at` DATETIME(6) NULL,
  `analysis_json` JSON NULL,
  `source_stats_json` JSON NULL,
  `last_attempt_at` DATETIME(6) NULL,
  `last_error_message` VARCHAR(500) NULL,
  `generated_at` DATETIME(6) NULL,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`teaching_class_id`),
  KEY `idx_teacher_analysis_status` (`analysis_status`, `updated_at`),
  CONSTRAINT `chk_teacher_analysis_status`
    CHECK (`analysis_status` IN ('IDLE', 'RUNNING', 'READY'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Course is the primary analysis unit. Class-wide and per-student results use
-- the same table and are separated by analysis_scope + student_id.
CREATE TABLE IF NOT EXISTS `teacher_course_analysis` (
  `teacher_id` BIGINT NOT NULL,
  `teaching_class_id` BIGINT NOT NULL,
  `course_id` INT NOT NULL,
  `analysis_scope` VARCHAR(16) NOT NULL,
  `student_id` BIGINT NOT NULL DEFAULT 0,
  `analysis_status` VARCHAR(16) NOT NULL DEFAULT 'IDLE',
  `analysis_json` LONGTEXT NULL,
  `source_stats_json` LONGTEXT NULL,
  `data_cutoff_at` DATETIME(6) NULL,
  `last_attempt_at` DATETIME(6) NULL,
  `last_error_message` VARCHAR(500) NULL,
  `generated_at` DATETIME(6) NULL,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`teacher_id`, `teaching_class_id`, `course_id`, `analysis_scope`, `student_id`),
  KEY `idx_teacher_course_analysis_lookup`
    (`teaching_class_id`, `course_id`, `analysis_scope`, `student_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Teacher-created focus groups, targeted practice and lesson examples.
CREATE TABLE IF NOT EXISTS `teacher_intervention` (
  `intervention_id` BIGINT NOT NULL AUTO_INCREMENT,
  `teacher_id` BIGINT NOT NULL,
  `teaching_class_id` BIGINT NOT NULL,
  `course_id` INT NULL,
  `title` VARCHAR(255) NOT NULL,
  `action_type` VARCHAR(32) NOT NULL,
  `knowledge_point_id` BIGINT NULL,
  `description` TEXT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
  `baseline_at` DATETIME(6) NOT NULL,
  `due_at` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`intervention_id`),
  KEY `idx_intervention_class_status_due` (`teaching_class_id`, `status`, `due_at`),
  KEY `idx_intervention_teacher_time` (`teacher_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `teacher_intervention_student` (
  `intervention_id` BIGINT NOT NULL,
  `student_id` BIGINT NOT NULL,
  `baseline_snapshot_json` JSON NULL,
  `latest_snapshot_json` JSON NULL,
  `assignment_status` VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  `training_session_id` VARCHAR(64) NULL,
  `started_at` DATETIME(6) NULL,
  `completed_at` DATETIME(6) NULL,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`intervention_id`, `student_id`),
  KEY `idx_intervention_student_status` (`student_id`, `assignment_status`, `updated_at`),
  KEY `idx_intervention_training_session` (`training_session_id`),
  CONSTRAINT `fk_intervention_student_parent`
    FOREIGN KEY (`intervention_id`) REFERENCES `teacher_intervention` (`intervention_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `teacher_intervention_question` (
  `intervention_id` BIGINT NOT NULL,
  `generated_question_id` VARCHAR(64) NOT NULL,
  `usage_type` VARCHAR(32) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`intervention_id`, `generated_question_id`, `usage_type`),
  KEY `idx_intervention_question` (`generated_question_id`, `created_at`),
  CONSTRAINT `fk_intervention_question_parent`
    FOREIGN KEY (`intervention_id`) REFERENCES `teacher_intervention` (`intervention_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `teacher_intervention_exercise_snapshot` (
  `snapshot_id` BIGINT NOT NULL AUTO_INCREMENT,
  `intervention_id` BIGINT NOT NULL,
  `source_exercise_id` BIGINT NOT NULL,
  `source_version` INT NOT NULL,
  `snapshot_json` LONGTEXT NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`snapshot_id`),
  UNIQUE KEY `uk_intervention_exercise_snapshot` (`intervention_id`, `source_exercise_id`),
  CONSTRAINT `fk_intervention_exercise_snapshot_parent`
    FOREIGN KEY (`intervention_id`) REFERENCES `teacher_intervention` (`intervention_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Latest source-grounded AI analysis for one knowledge point in one experiment.
CREATE TABLE IF NOT EXISTS `teacher_knowledge_analysis` (
  `analysis_id` BIGINT NOT NULL AUTO_INCREMENT,
  `teacher_id` BIGINT NOT NULL,
  `teaching_class_id` BIGINT NOT NULL,
  `course_id` INT NOT NULL,
  `knowledge_point_id` BIGINT NOT NULL,
  `analysis_status` VARCHAR(16) NOT NULL DEFAULT 'IDLE',
  `analysis_json` LONGTEXT NULL,
  `evidence_json` LONGTEXT NULL,
  `last_attempt_at` DATETIME(6) NULL,
  `last_error_message` VARCHAR(500) NULL,
  `generated_at` DATETIME(6) NULL,
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`analysis_id`),
  UNIQUE KEY `uk_teacher_knowledge_scope`
    (`teacher_id`, `teaching_class_id`, `course_id`, `knowledge_point_id`),
  KEY `idx_teacher_knowledge_lookup`
    (`teaching_class_id`, `course_id`, `knowledge_point_id`, `analysis_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Three independently editable/reviewable exercises produced by the analysis.
CREATE TABLE IF NOT EXISTS `teacher_knowledge_exercise` (
  `exercise_id` BIGINT NOT NULL AUTO_INCREMENT,
  `analysis_id` BIGINT NOT NULL,
  `exercise_role` VARCHAR(24) NOT NULL,
  `question_type` VARCHAR(32) NOT NULL,
  `stem` TEXT NOT NULL,
  `options_json` LONGTEXT NULL,
  `standard_answer` LONGTEXT NOT NULL,
  `explanation` LONGTEXT NULL,
  `difficulty` INT NOT NULL DEFAULT 1,
  `generation_rationale` TEXT NULL,
  `review_status` VARCHAR(24) NOT NULL DEFAULT 'PENDING_REVIEW',
  `review_comment` TEXT NULL,
  `source_version` INT NOT NULL DEFAULT 1,
  `reviewed_by` BIGINT NULL,
  `reviewed_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`exercise_id`),
  UNIQUE KEY `uk_teacher_knowledge_exercise_role` (`analysis_id`, `exercise_role`),
  KEY `idx_teacher_knowledge_exercise_review` (`review_status`, `updated_at`),
  CONSTRAINT `fk_teacher_knowledge_exercise_analysis`
    FOREIGN KEY (`analysis_id`) REFERENCES `teacher_knowledge_analysis` (`analysis_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
