version: "3.8"

services:
  web:
    container_name: directory-traversal-lab-web-1
    build: .
    ports:
      - "8095:80"
    depends_on:
      - db
    networks:
      - traversal-net
    volumes:
      - ./files:/var/www/html/files
    environment:
      - DB_HOST=db
      - DB_NAME=traversal_lab
      - DB_USER=root
      - DB_PASS=123456

  db:
    container_name: directory-traversal-lab-db-1
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: traversal_lab
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - traversal-net

volumes:
  dbdata:

networks:
  traversal-net: 
