[supervisord]
nodaemon=true
user=root

[program:vncserver]
command=/usr/bin/vncserver :1 -fg --localhost no -geometry 1440x900 -AcceptSetDesktopSize=1 -AlwaysShared -SecurityTypes VncAuth
autostart=true
autorestart=true
stdout_logfile=/var/log/vncserver.log
stderr_logfile=/var/log/vncserver-error.log

[program:set-wallpaper]
command=/usr/local/bin/set-wallpaper.sh
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/var/log/set-wallpaper.log
stderr_logfile=/var/log/set-wallpaper-error.log

[program:restart-panel-on-resize]
command=/usr/local/bin/restart-panel-on-resize.sh
autostart=true
autorestart=true
stdout_logfile=/var/log/restart-panel-on-resize.log
stderr_logfile=/var/log/restart-panel-on-resize-error.log
